version: '3'

services:
  # Backend API service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: category-mapping-api
    volumes:
      # Mount the main directory to access category data files
      - ./:/usr/src/app/data
    environment:
      - DATA_DIR=/usr/src/app/data
    ports:
      - "3000:3000"
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: category-mapping-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
